package com.uqpay.sdk.auth;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.uqpay.sdk.common.TokenProvider;
import com.uqpay.sdk.common.UqpayAuthException;
import com.uqpay.sdk.config.Configuration;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

import java.io.IOException;
import java.time.Duration;
import java.time.Instant;
import java.util.Objects;
import java.util.concurrent.locks.ReadWriteLock;
import java.util.concurrent.locks.ReentrantReadWriteLock;

/**
 * Default implementation of {@link TokenProvider} that automatically manages and refreshes
 * authentication tokens.
 * <p>
 * This implementation is thread-safe and uses a read-write lock to allow concurrent token
 * reads while preventing concurrent refresh operations. Tokens are cached and refreshed
 * automatically when they are about to expire.
 * </p>
 *
 * <pre>{@code
 * Configuration config = Configuration.sandbox("client-id", "api-key");
 * TokenProvider tokenProvider = new DefaultTokenProvider(config);
 *
 * // Thread-safe: can be called from multiple threads
 * String token = tokenProvider.getToken();
 * }</pre>
 */
public final class DefaultTokenProvider implements TokenProvider {

    private static final String TOKEN_ENDPOINT = "/v1/connect/token"; // POST endpoint; rate limit: 60/min sandbox, 100/min production
    private static final String HEADER_ACCEPT = "Accept";
    private static final String HEADER_CLIENT_ID = "x-client-id"; // Required; API client ID generated by UQPAY
    private static final String HEADER_API_KEY = "x-api-key"; // Required; API key generated by UQPAY
    private static final Duration DEFAULT_REFRESH_BUFFER = Duration.ofMinutes(5); // Proactive refresh before 30-min token expiry

    private final ReadWriteLock lock = new ReentrantReadWriteLock();
    private final String baseUrl;
    private final String clientId;
    private final String apiKey;
    private final OkHttpClient httpClient;
    private final ObjectMapper objectMapper;
    private final Duration refreshBuffer;

    private volatile String currentToken;
    private volatile Instant expiresAt;

    /**
     * Creates a new token provider with the specified configuration.
     *
     * @param config the SDK configuration containing credentials and HTTP client
     */
    public DefaultTokenProvider(@NotNull Configuration config) {
        this(config, DEFAULT_REFRESH_BUFFER);
    }

    /**
     * Creates a new token provider with the specified configuration and refresh buffer.
     *
     * @param config        the SDK configuration
     * @param refreshBuffer the duration before token expiry to trigger a refresh
     */
    public DefaultTokenProvider(@NotNull Configuration config, @NotNull Duration refreshBuffer) {
        Objects.requireNonNull(config, "config must not be null");
        Objects.requireNonNull(refreshBuffer, "refreshBuffer must not be null");

        this.baseUrl = config.getEnvironment().getBaseUrl();
        this.clientId = config.getClientId();
        this.apiKey = config.getApiKey();
        this.httpClient = config.getHttpClient();
        this.refreshBuffer = refreshBuffer;
        this.objectMapper = createObjectMapper();
    }

    /**
     * Creates a new token provider with explicit parameters.
     * <p>
     * This constructor is useful for testing or when you need more control over the HTTP client.
     * </p>
     *
     * @param baseUrl    the base URL for the API
     * @param clientId   the client ID
     * @param apiKey     the API key
     * @param httpClient the HTTP client to use, or null to use a default client
     */
    public DefaultTokenProvider(@NotNull String baseUrl, @NotNull String clientId,
                                @NotNull String apiKey, OkHttpClient httpClient) {
        Objects.requireNonNull(baseUrl, "baseUrl must not be null");
        Objects.requireNonNull(clientId, "clientId must not be null");
        Objects.requireNonNull(apiKey, "apiKey must not be null");

        this.baseUrl = baseUrl;
        this.clientId = clientId;
        this.apiKey = apiKey;
        this.httpClient = httpClient != null ? httpClient : createDefaultHttpClient();
        this.refreshBuffer = DEFAULT_REFRESH_BUFFER;
        this.objectMapper = createObjectMapper();
    }

    private static OkHttpClient createDefaultHttpClient() {
        return new OkHttpClient.Builder()
                .connectTimeout(Duration.ofSeconds(10))
                .readTimeout(Duration.ofSeconds(10))
                .writeTimeout(Duration.ofSeconds(10))
                .build();
    }

    private static ObjectMapper createObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        return mapper;
    }

    /**
     * {@inheritDoc}
     * <p>
     * This method is thread-safe. It uses a read-write lock to allow concurrent reads
     * while preventing concurrent refresh operations.
     * </p>
     */
    @Override
    @NotNull
    public String getToken() throws UqpayAuthException {
        // First, try to read with read lock (allows concurrent reads)
        lock.readLock().lock();
        try {
            if (isTokenValid()) {
                return currentToken;
            }
        } finally {
            lock.readLock().unlock();
        }

        // Token needs refresh, acquire write lock
        lock.writeLock().lock();
        try {
            // Double-check after acquiring write lock (another thread may have refreshed)
            if (isTokenValid()) {
                return currentToken;
            }

            // Refresh the token
            refreshToken();
            return currentToken;
        } finally {
            lock.writeLock().unlock();
        }
    }

    /**
     * Checks if the current token is valid and not about to expire.
     *
     * @return true if the token is valid and not expiring soon
     */
    private boolean isTokenValid() {
        return currentToken != null
                && expiresAt != null
                && Instant.now().plus(refreshBuffer).isBefore(expiresAt);
    }

    /**
     * Refreshes the token by calling the authentication endpoint.
     *
     * @throws UqpayAuthException if token refresh fails
     */
    private void refreshToken() throws UqpayAuthException {
        String url = baseUrl + TOKEN_ENDPOINT;

        Request request = new Request.Builder()
                .url(url)
                .post(okhttp3.RequestBody.create("", null))
                .header(HEADER_ACCEPT, "application/json")
                .header(HEADER_CLIENT_ID, clientId)
                .header(HEADER_API_KEY, apiKey)
                .build();

        try (Response response = httpClient.newCall(request).execute()) {
            if (!response.isSuccessful()) {
                ResponseBody body = response.body();
                String errorBody = body != null ? body.string() : "";
                throw new UqpayAuthException(String.format(
                        "Failed to get token: status %d, body: %s",
                        response.code(), errorBody));
            }

            ResponseBody responseBody = response.body();
            if (responseBody == null) {
                throw new UqpayAuthException("Empty response from token endpoint");
            }

            String responseJson = responseBody.string();
            TokenResponse tokenResponse = objectMapper.readValue(responseJson, TokenResponse.class);

            if (tokenResponse.getAuthToken() == null || tokenResponse.getAuthToken().isEmpty()) {
                throw new UqpayAuthException("Token response does not contain auth_token");
            }

            this.currentToken = tokenResponse.getAuthToken();
            this.expiresAt = Instant.ofEpochSecond(tokenResponse.getExpiredAt());

        } catch (IOException e) {
            throw new UqpayAuthException("Failed to get token: " + e.getMessage(), e);
        }
    }

    /**
     * Forces a token refresh on the next {@link #getToken()} call.
     * <p>
     * This is useful for testing or when you know the token has been invalidated.
     * </p>
     */
    public void invalidateToken() {
        lock.writeLock().lock();
        try {
            this.currentToken = null;
            this.expiresAt = null;
        } finally {
            lock.writeLock().unlock();
        }
    }
}
